// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdjfzdftagjnmvkkxuxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkamZ6ZGZ0YWdqbm12a2t4dXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzcxNTksImV4cCI6MjA2MTUxMzE1OX0.YoYLHaQmOtrBQg4k3UlKv8bRhHYitN4wESyTRtS016Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);